build:
  image: drone/golang
  environment:
    - CGO_ENABLED=0
    - GOPATH=/drone
  commands:
    - go get
    - go build
    - go test

publish:
  docker:
    username: drone
    password: $$DOCKER_PASS
    email: $$DOCKER_EMAIL
    repo: plugins/drone-git
    when:
      branch: master

plugin:
  name: Git
  desc: Clones a git repository.
  type: clone
  image: plugins/drone-git
  labels:
    - scm
    - vcs
    - git

secure:
  - DOCKER_EMAIL: B7xptE7CKOVCw19+hpaM+BPJZJg8wJgTn1sQNRMICFjAsWDI2DrCZqsp9eMxqE3XJL3qfhMVyl3agpINOFhTdnfRrzlc85VqYhHXrDiXo6AjFI4t2i1oivCos5XKDu1rEQvZmxnyoQLOtTZ8gIr2cD6c8zc9s0UZCLziwySQ5cHuHIxRftx14l4COIdYGrXA4u2w1YcBOu4+o7NeYVShKvxCNEsrkAhoEpe8qgb0vTZEjRltmc\/4KWfUSkySeKRFZDOWv1KiWQ6j3nccsLyb8gfVIg41LYoiWBfRE7F2uMAMR3YuTC43IXM6ydhq9M1AGlmNT3hjKe0R1Spq+yRsqg==
  - DOCKER_PASS: ECLQAnlq5wZSVuxxrD\/70\/PLPyW7OJQ3jy6rFufNXqNeAN5clmzNY+hh4PzO5zji2E9A2TSJGbJGQ3\/CFCdgtQcUBx5heoy4xEH0X236VSsuEDlGqj\/QIwSTF6AwB1oOjTNfwvgfREVJuAnQZSDDDvVonm3LGcyH2be9EUGioBPb0TYCI5TsLiI+ptdAkC2w+LSPZ\/UnGeT0UmySBZBUKSAsbZufoM5lc5V8HwK84MIqgla\/htb+qCNJfeUY2ULr90FCpydlDmDrmWjI2\/tDpXmIpfYKqiUKUYqZx0w5+WZlKqIMFrLcqtV8hruGi8GtMZCLYO0\/5\/TMe6OGzOUpGA==
