build:
  image: drone/golang
  environment:
    - CGO_ENABLED=0
    - GOPATH=/drone
  commands:
    - go get
    - go build
    - go test

publish:
  docker:
    username: $$DOCKER_USER
    password: $$DOCKER_PASS
    email: $$DOCKER_EMAIL
    repo: plugins/drone-git
    when:
      branch: master

notify:
  slack:
    webhook_url: $$SLACK_URL
    channel: #dev
    username: drone

plugin:
  name: Git
  desc: Clones a git repository.
  type: clone
  image: plugins/drone-git
  labels:
    - scm
    - vcs
    - git

