build:
  image: drone/golang
  environment:
    - CGO_ENABLED=0
    - GOPATH=/drone
  commands:
    - go get
    - go build
    - go test

publish:
  docker:
    username: drone
    password: $$DOCKER_PASS
    email: $$DOCKER_EMAIL
    repo: plugins/drone-git
    when:
      branch: master

plugin:
  name: Git
  desc: Clones a git repository.
  type: clone
  image: plugins/drone-git
  labels:
    - scm
    - vcs
    - git

secure:
  - DOCKER_EMAIL: CiyJfunXryiupUuiZ78LwHJh6a0f7_rworlqKNEWj0FNYWGwe7pxnbHVjd9gyA_T15_Vg4oNRHRJXeYNxNMooqX0mlFJH2lh1OFOC11rg6EayKlABBz13H1INmY6nPYkGaRCx4GWsD7hYwbMfNVHDEU3cynTnujbSIS-rN0qGrdckKXTypcytkEA9jwV_ckXNfr5UlI3kvYoDsQd4YhGMDtrtFe1O6owHCsa9JbgOyN-U6KAWZiUkV2E8fd5ImqnE-9m-WutFGgppQfss3m_BlxW9bzVbTGQzTNPQoJYw6MvOX0GvIa1zYFmsosrPJZJIrVT797uYLfq9O9ljumkQg==
  - DOCKER_PASS: ZvJnzmSvK-o90y1lNBxxQfKEVeQPoShkVCx2CIAFTXjR3klDFf6hCzhfKcs6ZVyoI6nOSKPpHZHP_SsG4EB3dq8LVHdoafC6cNnqIKomO3Kl_mknbGHwy8h9AVvED2uR1J5MufPavqiU1YGcCo8Mrq2resPBO5NZ_Tq7mmANEXDcHUiZ0WgD5Yh6tQ87C8Lfl7gDGAYV3r4orWPyCs-MR8HYTpMQjFqzFsfBpxJ9NHYDznAOgouB34O_YkMEwFNfK1AwwcX0ZTUqJnJk4DtO-yL9fSU3cNHl3IfepqX9hOo3OZVw2uAWsCPd3-WrSn-DeFd5CaICCT0V5Lm8LKeopg==

