build:
  image: drone/golang
  environment:
    - CGO_ENABLED=0
    - GOPATH=/drone
  commands:
    - go get
    - go build
    - go test

publish:
  docker:
    username: drone
    password: $$DOCKER_PASS
    email: $$DOCKER_EMAIL
    repo: plugins/drone-git
    when:
      branch: master

plugin:
  name: Git
  desc: Clones a git repository.
  type: clone
  image: plugins/drone-git
  labels:
    - scm
    - vcs
    - git

secure:
  DOCKER_EMAIL: YGaogqneDFIH_bffTQQvIuRTluXmBKhXPuCyINWnwyC57wknhkAy6CqPdpDobreOZ58jKnWAZG_KZ8Yw9yjbhzALtUgRw3Wkya1UInlG6E2E3HqK_ovupUw8-UUIa-hRN8rM2rbGHa2hbvyVj-B6fb_AsoOx5Mbr91yF67JwxtnU0g97XnPDQEokrnoOfenFWP92Xryk07xjuEOVxsRBuk4OPc97eLup-RMy4g3U9jGOhv05FafDvnqZwoUSA_SZBAD_Zr5TmJjJVeq2FxyWn96md1VefQWHGy1aeT2BM3GdFEJSN9s6P42pS3VHe-lFzkkuU97jyUbcLFy69fEr3w
  DOCKER_PASS: mibUhQU6iyt05DCrMVfraPtY7CVdKsClV5RHIc3zFuT4Zx7ZhbiSoO13xbBjNuRGHt7uXO4FPGmZ-gRqmtXdbQ3EZ6Y6l1ldSvU3dIALuFbGARuLmculBqbs4RkKZN1XQ-05bqDFxHbZXMACNFuaRv0CZk8Pknm-sA_C6VYO0TULzzfAC96sOo4Kg9PMIJ8iiEpa57Ch8JNiE_jFZxHvySTeWG2l92divilGMrxP4xCGO6h0qXcwQH8tPg5v0JhUgc3bCLSjgXLo-sEIc6fk0lDrMc92M5t1mR-B5TO9xQPS8y5Pdr13_CQNle0CNB7jG60kcxyBNJHeGTWjPhNc0A

