pipeline:
  test:
    image: golang:1.6
    environment:
      - CGO_ENABLED=0
      - GO15VENDOREXPERIMENT=1
      - GOPATH=/drone
    commands:
      - go vet
      - go test -cover -coverprofile=coverage.out
      - go build -ldflags "-s -w -X main.build=$DRONE_BUILD_NUMBER"
  docker:
    storage_driver: overlay
    repo: plugins/git
    tag: [ "latest", "1.0", "1" ]
    when:
      branch: master
      event: push

plugin:
  name: Git
  desc: Clones a git repository
  type: clone
  image: plugins/git
  labels:
    - scm
    - vcs
    - git
