build:
  image: drone/golang
  environment:
    - CGO_ENABLED=0
    - GOPATH=/drone
  commands:
    - go get
    - go build
    - go test

publish:
  docker:
    username: drone
    password: $$DOCKER_PASS
    email: $$DOCKER_EMAIL
    repo: plugins/drone-git
    when:
      branch: master

plugin:
  name: Git
  desc: Clones a git repository.
  type: clone
  image: plugins/drone-git
  labels:
    - scm
    - vcs
    - git

secure:
  - DOCKER_EMAIL: |
      puL6SfQCc/IQX1hVipCWMYB7mWrIipUzCqG+vofTCDnWhKqSzJTPNeeFFa4Lqqd7zxSKCD4OipZZlkusN8Jj8nDVo8L3qF4zmitt/qPRJCWoH5FQ7qocBDQDh/hiYCArQ84wwIBufni//zfIB+L6+dx2RZPk9e4XoCdRv2lDzaquKGBokDr/HJoO9TCkWcuufwwgxKt+sOsxkFdH0rX3rG1vlw/8Q6YvvrG46nvOGEst1bXbSf/C7QZvtgYejKFUp2BdnqyC3Gvp5Ul84sxIDxhP45Of1KQJalkRxx2YUYik1cvG3XO2EPeVKMNklhKu7dEVhTx94ALHjtHKJMwLUQ==
  - DOCKER_PASS: |
      qRou5daRMHWtBdIRr0xKOdJpG9/Cj/nNJBR8BOQKgjlGsEdDliRN+SjKmFC1G0MkdcwjR3jr+AL1xQTLUtNu93eT2fg8ME9Fp3WLpHmcwybRT92uqyr73J2puXJSKIOBS+Ely0K8oxuqLtMk6+/zRvs4tk22ZfkM4Oshn5lePhSTNvhQNFpaACDwfLvmd2Od3tC85zUJHqKYovFDpp5OqKGLQImp6IPejwlgnsuptMZXpEkQX2uwEYNpY/D8DOLpSHTmLViL6QkHGha2excLI1U4OlozXm+q0b0zmMrHEAbzWBMkgG8cxbM4dv4qvHdOlpGw+tP6qu2C/BOkaFA37w==

