build:
  test:
    image: golang:1.5
    environment:
      - CGO_ENABLED=0
      - GO15VENDOREXPERIMENT=1
    commands:
      - go vet
      - go test -cover -coverprofile=coverage.out
      - go build -ldflags "-s -w -X main.build=$DRONE_BUILD_NUMBER"
    when:
      event: push

publish:
  coverage:
    when:
      branch: master
  docker:
    username: $$DOCKER_USER
    password: $$DOCKER_PASS
    email: $$DOCKER_EMAIL
    repo: plugins/git
    tag: latest

plugin:
  name: Git
  desc: Clones a git repository
  type: clone
  image: plugins/git
  labels:
    - scm
    - vcs
    - git
