clone:
  git:
    image: plugins/git:next

pipeline:
  build-push:
    pull: true
    image: golang:1.16
    commands:
      - "go build -v -ldflags \"-X main.version=${DRONE_COMMIT_SHA:0:8}\" -a -tags netgo -o release/linux/amd64/drone-git"
    environment:
      - CGO_ENABLED=0
    when:
      event: push

  build-tag:
    pull: true
    image: golang:1.16
    commands:
      - "go build -v -ldflags \"-X main.version=${DRONE_TAG##v}\" -a -tags netgo -o release/linux/amd64/drone-git"
    environment:
      - CGO_ENABLED=0
    when:
      event: tag

#- name: executable
#  pull: always
#  image: golang:1.11
#  commands:
#  - ./release/linux/amd64/drone-git --help

#- name: dryrun
#  pull: always
#  image: plugins/docker:linux-amd64
#  settings:
#    daemon_off: false
#    dockerfile: docker/Dockerfile.linux.amd64
#    dry_run: true
#    password:
#      from_secret: docker_password
#    repo: plugins/git
#    tags: linux-amd64
#    username:
#      from_secret: docker_username
#  when:
#    event:
#    - pull_request

# publish
#  pull: always
#  image: plugins/docker:linux-amd64
#  settings:
#    auto_tag: true
#    auto_tag_suffix: linux-amd64
#    daemon_off: false
#    dockerfile: docker/Dockerfile.linux.amd64
#    password:
#      from_secret: docker_password
#    repo: plugins/git
#    username:
#      from_secret: docker_username
#  when:
#    event:
#      exclude:
#      - pull_request

#trigger:
#  ref:
#  - refs/heads/master
#  - "refs/tags/**"
#  - "refs/pull/**"

depends_on:
- testing