clone:
  git:
    image: plugins/git:next

pipeline:
  vet:
    pull: true
    image: golang:1.16
    commands:
      - go vet ./...

  test:
    pull: true
    image: golang:1.16
    commands:
      - go test -cover ./...